title: Pranav Kapale
logo: /Assets/Image/pranav_kapale.png
# description: A passionate software engineer with a knack for problem-solving and a love for technology.
author: Pranav Kapale
theme: jekyll-theme-minimal